# Generated by Django 6.0.5 on 2026-05-21 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("subject", models.CharField(max_length=150)),
                ("start_time", models.CharField(blank=True, max_length=10, null=True)),
                ("end_time", models.CharField(blank=True, max_length=10, null=True)),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rate_applied", models.DecimalField(decimal_places=2, max_digits=6)),
                ("total_pay", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_custom", models.BooleanField(default=False)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
