# Generated by Django 6.0.5 on 2026-05-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyllabusTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.CharField(max_length=50)),
                ("year_level", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=150)),
                ("subtopic", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In Progress", "In Progress"),
                            ("Backlog", "Backlog"),
                        ],
                        default="Backlog",
                        max_length=20,
                    ),
                ),
                ("last_updated", models.DateField(auto_now=True)),
                ("covered_by", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResourceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=150)),
                ("file_name", models.CharField(max_length=200)),
                ("file_type", models.CharField(max_length=20)),
                ("drive_url", models.URLField(max_length=500)),
                ("week_number", models.IntegerField(default=21)),
                (
                    "syllabus_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="resources.syllabustracker",
                    ),
                ),
            ],
        ),
    ]
