# Generated by Django 6.0.5 on 2026-05-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceitem",
            name="month",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="resourceitem",
            name="week_string",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
